<?php

/**
 * @file
 * Contains user_links.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_links_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_links module.
    case 'help.page.user_links':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide dynamic user links.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_links_theme($existing, $type, $theme, $path) {
  return [
    'user_links' => [
      'variables' => [
        'links' => [],
      ],
    ],
  ];
}
